import { Alexandria } from "next/font/google";
import Script from "next/script";

const inter = Alexandria({
  subsets: ["arabic", "latin", "latin-ext", "vietnamese"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// components
import Cursor from "~/components/layout/Cursor";
import Preloader from "~/components/layout/Preloader";
import Scrollbar from "~/components/layout/Scrollbar";
import Menu from "~/components/layout/Menu";
import Curtain from "~/components/layout/Curtain";
import Frame from "~/components/layout/Frame";

// css
import "~/assets/css/plugins/bootstrap-grid.css";
import "~/assets/css/plugins/swiper.min.css";
import "~/assets/css/style.css";

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      {/* <Head>
        <link rel="stylesheet" href="/css/plugins/font-awesome.min.css" /> */}
      {/* </Head> */}
      <body className={inter.className}>
        <div className="mil-wrapper" id="top">
          {/* preloader */}
          <div>
            <Cursor />
            <Preloader />
            <Scrollbar />
            <Menu />
            <Curtain />
            <Frame />

            {/* content */}
            <div className="mil-content">
              <div id="swupMain" className="mil-main-transition">
                {children}
              </div>
            </div>
          </div>
        </div>

        {/* js */}
        <Script src="/js/plugins/jquery.min.js" />
        <Script src="/js/plugins/swup.min.js" />
        <Script src="/js/plugins/swiper.min.js" />
        <Script src="/js/plugins/fancybox.min.js" />
        <Script src="/js/plugins/gsap.min.js" />
        <Script src="/js/plugins/smooth-scroll.js" />
        <Script src="/js/plugins/Scrolltrigger.min.js" />
        <Script src="/js/plugins/ScrollTo.min.js" />
        <Script src="/js/main.js" />
      </body>
    </html>
  );
}
